$(document).ready(function(){
    $(".all").click(function(){
        $("#p1").toggle();
        $("#img1").toggle();
    });
    $(".all1").click(function(){
        $("#p2").toggle();
        $("#img2").toggle();
    });
})